### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ritazh** [Azure/kubernetes-kms#11]

**Comment by khenidak** [comment]
@jackfrancis what is your thoughts for CI within `acs-engine` for this?

**Comment by jackfrancis** [comment]
Will there be a "kubernetes-kms addon/extension" for acs-engine? In that context it'd make sense to re-use acs-engine E2E.

**Comment by ritazh** [comment]
@jackfrancis The azure kms grpc service will be added as an addon for acs-engine. But this service is a standalone, which is why I wanted to add CI here to ensure whatever we update here is fully tested before we push the image. What would you recommend?

**Comment by jackfrancis** [comment]
Doing both makes sense in the idea. There are surely CI considerations to gate against unhealthy code changes here. For acs-engine, we'd add test coverage at the Kubernetes API layer to validate that the underlying kms addon implementation behaves as we expect it to in a Kubernetes cluster.

**Comment by ritazh** [comment]
>Doing both makes sense

Can I get your help to enable Circleci here 🤓 

> validate that the underlying kms addon implementation behaves as we expect it to in a Kubernetes cluster

Is there a specific test you had in mind? If this doesnt work as intended, then none of the secrets will be created during service account creation, in turn controller-manager will fail and api server will fail.

**Comment by ritazh** [comment]
@julienstroheker I added https://github.com/Azure/kubernetes-kms/pull/12/commits/42e0953a427be29b3edad7441122cfa74657d1e0 to fix the build.
