### ISSUE TITLE
Update README.md to remove references to aks-engine

### ISSUE THREAD

**Issue by aramase** [Azure/kubernetes-kms#136]
[aks-engine](https://github.com/Azure/aks-engine#project-status) is deprecated. 

- We should restructure our readme to reference general instructions for setup, rotation instead of the aks-engine cluster config example.
- Add reference to AKS docs when https://github.com/Azure/AKS/issues/845 is complete.

**Comment by sozercan** [comment]
AKS docs: https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption
