### ISSUE TITLE
kubernetes-kms started looking for a storage account instead of the key vault

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/kubernetes-kms#25]
kube-controller-manager failed to start with the next error:
`2018-07-08T14:42:28.82944156Z stderr F E0708 14:42:28.829339       1 tokens_controller.go:261] error synchronizing serviceaccount kube-system/cronjob-controller: Internal error occurred: rpc error: code = Unknown desc = failed to create key, error: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/my-akv' under resource group 'my-rg' was not found."`

A week ago everything worked fine. No changes in the deployment playbooks. As you see, it starts looking for a storage account with the name of the key-vault service (exists).

**Comment by ritazh** [comment]
Hi @IvanovOleg, thanks for reporting this. yes we have changed our design to include a storage account to handle key creation racing condition. Please refer to this PR: #23.

To fix this issue, you need to create a storage account in the same resource group as the keyvault instance. But you cannot have `-` in the name.

**Comment by ritazh** [comment]
@IvanovOleg can you pls give the manual install update a try to see if this fixes your issue? https://github.com/Azure/kubernetes-kms/pull/27

**Comment by IvanovOleg** [comment]
@ritazh I've removed KMS from my kubernetes deployment process. I can close the issue.
