### ISSUE TITLE
Release Image Tagging

### ISSUE THREAD

**Issue by keyoke** [Azure/kubernetes-kms#28]
Hi,
Recently we ran into issues with newer versions pf the k8s azure KMS plugin as acs-engine is always pulling the following image "microsoft/k8s-azure-kms:latest" when bringing up the KMS services - https://github.com/Azure/acs-engine/blob/8d7d7202a2ccb57efacb6a7f937980c147785bb8/parts/k8s/artifacts/kubernetesazurekms.service#L16

As you can imagine this is not ideal, I would suggest that we introduce some docker image versioning so that if we deploy using a specific version of acs-engine + k8s Azure KMS then deployment works as expected.

Thanks

**Comment by ritazh** [comment]
@keyoke Agreed! Will make the necessary changes here and in acs-engine. Thanks for reporting this!

**Comment by ritazh** [comment]
Fixed in https://github.com/Azure/kubernetes-kms/pull/29 and https://github.com/Azure/acs-engine/pull/3459
