### ISSUE TITLE
AKS Support

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/kubernetes-kms#3]
Hello!

In order to use KKMS now, we need to change the manager nodes manually (for now).

Is there any plan/eta on when we will be able to use it with AKS? Right now it is not possible as we can't modify the managers since they are self-managed by Azure.

Thanks! Great work!

Best regards,
Gutemberg

**Comment by ritazh** [comment]
Thanks for the feedback @galvesribeiro! We need to first integrate this with [acs-engine](https://github.com/Azure/acs-engine/). I'm working on that now. Will let you know as soon as acs-engine is supported. So maybe you can test there. Please check back here with acs-engine support, then AKS support in the future.

**Comment by galvesribeiro** [comment]
Thanks! Please notify us about the progress on this issue so people can follow it.

Thank you! Great work!

**Comment by khenidak** [comment]
fyi @slack

**Comment by LoungeFlyZ** [comment]
This would be really great @ritazh .. thanks a lot for tackling this!

**Comment by alexeldeib** [comment]
@ritazh is this still in progress? Would be interested in closer integration between Key Vault and AKS.

**Comment by ritazh** [comment]
Hi @alexeldeib 👋 We definitely hear you! It is in our backlog to bring this feature to AKS. 
FYI @seanmck @sauryadas

In the meantime, Kubernetes-kms can be used today on acs-engine, here is an example: https://github.com/Azure/acs-engine/blob/master/examples/kubernetes-config/kubernetes-keyvault-encryption.json#L8

**Comment by erick-thompson** [comment]
Any update on when it might work with AKS?

**Comment by hberrayana** [comment]
Hello @ritazh is there any progress made in this? If not do you have an estimated release date please?

**Comment by sauryadas** [comment]
Unfortunately this is still in the backlog and not scheduled until the end of the year

**Comment by galvesribeiro** [comment]
Guys you can try this: https://github.com/Azure/kubernetes-keyvault-flexvol

Works flawless.

**Comment by aramase** [comment]
Please use https://github.com/Azure/AKS/issues/845 for tracking the integration.
