### ISSUE TITLE
UpdateKMSProvider is not robust

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kubernetes-kms#38]
Hi,

We're using a modified version of `azure.json`. [This line](https://github.com/Azure/kubernetes-kms/blob/f361265169d7e7ba56390ac1931afc983175af1d/oauth.go#L179) in `UpdateKMSProvider` assumes `providerKeyVersion` is the last line in JSON as it doesn't end with a comma. This will cause syntax error when `azure.json` looks like:

```json
  "providerKeyName": "k8s",
  "providerKeyVersion": "xxx"
  "maximumLoadBalancerRuleCount": 240
}
```

Applying string manipulation to a JSON file is usually buggy. I strongly suggest you using a standard JSON parser rather than assuming it's in an acs-engine generated format.

**Comment by ritazh** [comment]
@ArchangelSDY thanks for the feedback! Will definitely update this.
