### ISSUE TITLE
AAD too many requests

### ISSUE THREAD

**Issue by ArchangelSDY** [Azure/kubernetes-kms#52]
We got 429 Too Many Requests error from AAD after we restarted API Server. It lasted for quite a while and caused API Server outage since all secrets were unable to be read.

After reading the code, I find that each time KMS makes a request to KeyVault, it calls `getKey` first. Inside it creates a new KeyVaultClient along with a new AAD token, which means a new call to AAD later. I think that's unnecessary because you only need to create a new key when it doesn't exist. And once it's created, its version is persisted and never changes. We don't have to check it in each encryption or decryption calls.

I'm wondering if we can move the `getKey` call to KMS starting time and save the KeyVaultClient in `KeyManagementServerService` for later reuse. In this case, AAD token is also able to be reused. If you can confirm this, I'm happy to submit a PR :)

@ritazh

**Comment by ritazh** [comment]
Apologies for the long delay on this issue. Will fix this in the next release.
