### ISSUE TITLE
Wrap keys using AES KeyWrap instead of RSA

### ISSUE THREAD

**Issue by mamckee** [Azure/kubernetes-kms#61]
RSA encrypted DEKs are 256 bytes. Using AES KeyWrap to encrypt the DEKs shrinks this to 40 bytes and improves performance.

**Comment by amitbapat** [comment]
There is no plan to support AES keys in Key Vault in near future.

**Comment by aramase** [comment]
Thank you for chiming in on the issue @amitbapat.

Closing this issue as it's not currently in plan. Please feel free to reopen if you've any questions.
