### ISSUE TITLE
Handle key rotation

### ISSUE THREAD

**Issue by ritazh** [Azure/kubernetes-kms#8]

**Comment by pjbgf** [comment]
@ritazh it would be interesting to see what will be achieved on this space. Is this issue focused towards rotation of KeyVault keys, or is there also plans to help rotating credentials with other Azure technologies such as Sql Azure, Storage Accounts, Service Bus, SPNs, CosmosDb? We are currently defining our strategy around that topic and would be great if this was already considered as part of this integration between k8s and kv.

**Comment by khenidak** [comment]
iirc key rotation is a feature planned on upstream. Once the interfaces are implemented there we can extend our own kms accordingly. 

@ritazh -- Can you confirm?

**Comment by ritazh** [comment]
@pjbgf This issue is focused on how this service needs to handle encryption and decryption after KeyVault key rotation. Today the service will always use the latest key version if no key version is provided.

**Comment by vtiwari227** [comment]
Is there a update on this ? is key rotation feature is on roadmap ?

**Comment by ritazh** [comment]
This feature is in on the roadmap.

**Comment by ngrigoriev** [comment]
I think the key rotation is a critical feature, do you have any updates on the roadmap? Thanks!

**Comment by m-deepakraja** [comment]
Any update on this feature enhancement? Key rotation is an important and critical feature.

**Comment by aramase** [comment]
As of [v0.0.11] release, we officially support BYOK and rotation. Rotation needs to be manually performed. Here are docs for 
1. Manual install the new kms plugin: https://github.com/Azure/kubernetes-kms/blob/master/docs/manual-install.md
2. Rotation: https://github.com/Azure/kubernetes-kms/blob/master/docs/rotation.md

**Comment by aramase** [comment]
Closing this issue with the docs for key rotation.
